spring.application.name=smarticu

# =========================
# H2 DATABASE CONFIG
# =========================
spring.datasource.url=jdbc:h2:mem:smarticu
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# THYMELEAF
# =========================
spring.thymeleaf.cache=false

# =========================
# SERVER PORT
# =========================
server.port=${PORT:8080}

# =========================
# H2 CONSOLE
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console